# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            /dev/random
tagline:          'coding and rambling'
description:      'coding and rambling'
url:              
baseurl:          /

author:
  name:           Daniel Gyarmati
  url:            https://www.devslashrand.com/

paginate:         10
paginate_path: 	  blog/page:num

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

url:            https://www.devslashrand.com/

plugins:
  - jekyll-paginate
  - jekyll-gist
  - kramdown
  - jekyll-sitemap
  - jekyll-seo-tag
  
excerpt_separator: <!--more-->